In [9]:
using Plots
using PyCall

In [103]:
@pyimport pandas as pd
@pyimport numpy as np
@pyimport matplotlib.pyplot as plt

In [11]:
using CSV

In [7]:
a=axes([3,2,1])[1]|> collect
a

3-element Array{Int64,1}:
 1
 2
 3

In [49]:
300 .* [0.4,0.5,0.6,0.7]

4-element Array{Float64,1}:
 120.0
 150.0
 180.0
 210.0

In [126]:
#Samplig Rate-MF1
x= [120 , 150 ,180 , 210]
y = [[0.8660023600367116,0.8576607866435122 , 0.8321158008658007 , 0.8797463141421629 ],
    [0.8660023600367116,0.8566607866435122 , 0.8357411337543788 , 0.8797463141421629 ]]
plot(x,y,
    xlabel = "Sampling Rate /Hz",
    ylabel = "MF1",
    label=["Raw Signal","Raw Signal+Noise"],
    ylim=[0.7,1],
    #line = (:circle),
    fontfamily=(font(20)),
    markershape=(:circle),
    xtickfont = font(20),
    ytickfont = font(20), 
    legendfontsize =(20),
    titlefontsize =(20),
    guidefontsize =(20),
    #line = ((:dash)),
    dpi=512,
    )
#plot!( fontfamily=(font(30)),)
    #title="Sampling Rate-MF1")
savefig("Sampling_Rate_MF1")

In [108]:
plotattr("Axes")

ErrorException: There is no attribute named Axes

In [146]:
#Interval
x=collect(512:256:1280)./300
y=[[0.8588466027194819,0.8961476905243329,0.9283312470853888,0.9349158586871726],
    [0.9005631958087753,0.9037970513137303,0.9192259815189256,0.9367703722574277],
    [0.8749784195515409,0.9072420532156595,0.9173222772777834,0.9607850318957359],
    [0.8717294017516405,0.9198308760947753,0.9207899305555556,0.9569987482512333],
    [0.8588466027194819,0.9287109375,0.9226285108638049,0.9374523553018705]]
styles = filter((s->begin
                s in Plots.supported_styles()
            end), [:solid, :dash, :dot, :dashdot, :rect])
styles = reshape(styles, 1, length(styles))

plot(x,y,label=([ "0.3","0.5","0.7","0.9","All"]),
    xlabel = "Time Interval Length /s",
    ylabel = "MF1",
    xlim=[1.5,4.5],
    dpi=512,
    legend=(:bottomright),
    linealpha = 1,
    markershape=([:circle]),
    line = (5,styles),
    xtickfont = font(20),
    ytickfont = font(20), 
    legendfontsize =(16),
    titlefontsize =(20),
    guidefontsize =(20),
    )
    #title="Time Interval Length-MF1")
savefig("Time_Interval_Length_MF1")

In [69]:
styles,string

(Symbol[:solid :dash :dot :dashdot], string)

In [81]:
plotattr("plot")

ErrorException: There is no attribute named plot

In [34]:
using Statistics

LoadError: syntax: extra token "kde" after end of expression

In [25]:
?Statistics

search: Statistics



```
Statistics
```

Standard library module for basic statistics functionality.


In [30]:
mean102=np.load("102dots_ds_mean_std.npy")

322670×2 Array{Float32,2}:
  1.52344    46.7626 
 -2.27344    45.613  
  2.29688    53.3044 
 -0.820313   59.5762 
 -0.101563   77.6664 
 -0.472656   58.5732 
  0.0351563  60.0327 
  0.714844   55.7826 
  4.16797    50.1903 
 -4.29688    54.2203 
  0.175781   60.8995 
 -0.625      54.504  
  0.605469   52.1354 
  ⋮                  
  0.234375   62.8881 
 -0.757813   58.462  
 -1.44922    56.8103 
  0.917969   54.3078 
  2.35547    52.8844 
 -0.523438   49.9965 
 -1.46875    58.533  
 -0.585938   62.7031 
  0.148438    9.73764
  0.835938   64.7109 
 -0.632813   64.5593 
 -0.0976563  59.9239 

In [45]:
s = pd.Series(mean102[:,1])
ax = s.plot.kde()
plt.show()

In [54]:
plot(s.data.plot.kde())

ErrorException: type Array has no field plot

In [58]:
?pd.Series(mean102[:,1]).plot.kde()

```
PyObject(juliavar)
```

This converts a julia variable to a PyObject, which is a reference to a Python object. You can convert back to native julia types using `convert(T, o::PyObject)`, or using `PyAny(o)`.

Given `o::PyObject`, `o[:attribute]` is equivalent to `o.attribute` in Python, with automatic type conversion.

Given `o::PyObject`, `get(o, key)` is equivalent to `o[key]` in Python, with automatic type conversion.


In [48]:
show(ax)

PyObject <matplotlib.axes._subplots.AxesSubplot object at 0x7f60699d5ac8>

In [60]:
using Distributions

ArgumentError: ArgumentError: Package Distributions not found in current path:
- Run `import Pkg; Pkg.add("Distributions")` to install the Distributions package.
